reports:
  exlcude_contracts:
    - SafeMath
dependencies:
  -   OpenZeppelin/openzeppelin-contracts@4.4.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1'
autofecth_sources: True
dotenv: .env
networks:
  default: development
  development:
    verify: False
  rinkeby:
    verify: False
  ganache:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}


